enum error_codes
{
	ERR_NO_ERROR=0,
	ERR_TIMEOUT,
	ERR_MEDIA_READ,
	ERR_MEDIA_READ_SECTOR_NOT_FOUND,
	ERR_MEDIA_READ_NO_INDEX,
	ERR_MEDIA_WRITE,
	ERR_MEDIA_WRITE_SECTOR_NOT_FOUND,
	ERR_MEDIA_WRITE_NO_INDEX,
	ERR_READ_FILE_ACCESS,
	ERR_WRITE_FILE_ACCESS,
	ERR_LBA_CHANGE_FAILURE,
	ERR_MEM_ALLOC,
	ERR_SYSLIB_LOAD,
	ERR_DRIVE_NOT_FOUND,
	ERR_TRACK0_SEEK,
	ERR_MEDIA_ATTACH,
	ERR_INVALID_PARAMETER,
	ERR_INVALID_HANDLER,
	ERR_BAD_DRIVE_ID,
	ERR_CONFIG_FILE_ACCESS,
	ERR_CONFIG_FILE_VERSION,
	ERR_CONFIG_FILE_SIGN
};

void error_message_box(ui_context * ctx, int error_code);

