#define MAX_NUMBER_OF_SLOT 1000

#define FILELIST_Y_POS 1
#define HELP_Y_POS 1

#define CURDIR_Y_POS 0

#define MAX_PAGES_PER_DIRECTORY 256

#define FONT_FOLDER_ICON 10
#define FONT_FILE_ICON 11

#define MAX_X_RESOLUTION 640
#define MAX_Y_RESOLUTION 400

#define FONT_MIN_SIZE_Y 6
#define MAX_FILES_PER_SCREEN ( ( MAX_Y_RESOLUTION / FONT_MIN_SIZE_Y ) )

