
keyboard_funct_mapper keysmap[]=
{
	{FCT_UP_KEY,72},
	{FCT_DOWN_KEY,80},
	{FCT_LEFT_KEY,75},
	{FCT_RIGHT_KEY,77},
	{FCT_SELECT_FILE_DRIVEA,28},
	{FCT_SAVE,67},
	{FCT_REBOOT,66},
	{FCT_CLEARSLOT,14},
	{FCT_HELP,98},
	{FCT_SAVEREBOOT,68},
	{FCT_SELECTSAVEREBOOT,65},
	{FCT_OK,57},
	{FCT_SHOWSLOTS,15},
	{FCT_SEARCH,59},
	{FCT_TOP,53},
	{FCT_CHGCOLOR,60},
	{FCT_EMUCFG,61},
	{FCT_ESCAPE,1},
	{FCT_NO_FUNCTION,0x00}
};
